name: Fidemo
favicon: null
layout_spectrum: 0.7924211698118597
typography_spectrum: 0.5221821467857808
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9615145067218691
  lightness: 0.02606992539949715
  saturation: 0.1626087697222829
  rhythmicContrast: 0.642914084950462
purpose: []
